from django.conf.urls import patterns, url
from django_tables2_simplefilter import FilteredSingleTableView
from Web.views import *

urlpatterns = patterns('Web.views',
    url(r'^$', 'index'),
	url(r'^connections/$', FilteredSingleTableView.as_view(template_name='connections/index.html',
                                        table_class=ConnectionsTable,
                                        model=Connection,
                                        table_pagination={"per_page": 15}),
                                        name='Connections'),
    url(r'^connections/(?P<connection_id>\d+)/', 'cdetail'),
    url(r'^downloads/', FilteredSingleTableView.as_view(template_name='downloads/index.html',
                                        table_class=DownloadsTable,
                                        model=Download,
                                        table_pagination={"per_page": 15}),
                                        name='Downloads'),
    url(r'^graphs/protocols/$', 'protocols'),
    url(r'^graphs/protocolsdata/$', 'protocolsData'),
    url(r'^graphs/ports/$', 'ports'),
    url(r'^graphs/portsdata/$', 'portsData'),
    url(r'^graphs/urls/$', 'urls'),
    url(r'^graphs/urlsdata/$', 'urlsData'),
    url(r'^graphs/malware/$', 'malware'),
    url(r'^graphs/malwaredata/$', 'malwareData'),
    url(r'^graphs/ips/$', 'ips'),
    url(r'^graphs/ipsdata/$', 'ipsData'),
	url(r'^graphs/connections/$', 'connections'),
    url(r'^graphs/connectionsdata/$', 'connectionsData'),
    url(r'^graphs/timeline/$', 'timeline'),
    url(r'^graphs/conncountries/$', 'connCountries'),
    url(r'^graphs/ipscountries/$', 'ipsCountries'),
    url(r'^maps/attackers/$', 'attackers'),
    url(r'^maps/countries/$', 'countries'),
)